services:
  mysql:
    image: mysql:8.0
    container_name: biblioteca-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: biblioteca_db
    ports:
      - "3307:3306"   # host:contenedor
